project:
  type: book

book:
  title: "cdad-book"
  author: "Insper"
  date: "22/01/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - 01-tipos-variaveis.ipynb
    - 02-organizacao-dados-taxas.ipynb
    - 03-medidas-posicao-variabilidade.ipynb
    - 04-visualizacao-seaborn.ipynb
    - 05-amostras-populacoes.ipynb
    - 06-probabilidade-cnormal.ipynb
    - 07-testes-hipoteses.ipynb
    - 08-correlacao-regressao.ipynb
    - 09-modelos-classificacao.ipynb
    - 10-corporativo.ipynb
    - 11-openai.ipynb
    - resumo.qmd
    - refs.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

filters:
  - pyodide


