on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]

name: Deploy Preview

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Check out base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base

      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: head

      - name: Check modified files
        id: check
        run: |
          cd head
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Security check: ensure workflow files weren't modified
          if echo "$CHANGED_FILES" | grep -q "^\.github/workflows/"; then
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "❌ Workflow files were modified. Deploy preview blocked for security."
            exit 0
          fi
          
          # Check if only 12-exercicios.qmd was modified
          if [ "$CHANGED_FILES" = "12-exercicios.qmd" ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "✅ Only 12-exercicios.qmd was modified. Deploy preview will be created."
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "❌ Other files were modified. Deploy preview will NOT be created."
            echo "Only modifications to 12-exercicios.qmd are allowed for deploy previews."
          fi

  build-preview:
    needs: check-files
    if: needs.check-files.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
          fetch-depth: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install Python dependencies
        run: uv sync

      - name: Render Quarto project
        run: |
          quarto render
        env:
          QUARTO_PYTHON: .venv/bin/python

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './_book'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy preview for PR #${{ github.event.pull_request.number }}"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  skip-preview:
    needs: check-files
    if: needs.check-files.outputs.should_deploy == 'false'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Deploy preview skipped**\n\nOnly modifications to `12-exercicios.qmd` are allowed for deploy previews.\nThis PR modifies other files.'
            })
